# Generated by Django 4.0.4 on 2022-04-16 20:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rent',
            name='fromm',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='rent',
            name='to',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
